name: ci-push
run-name: wokflow ci-push sendo executado
on:
  push:
    branches:
      - main
jobs:
  executa-projeto:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o clone do repositório e muda para a branch correta (checkout)
        uses: actions/checkout@v5

      - name: Instalar o node na versão 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Instalar as dependências de execução
        run: npm install

      - name: Executa o executa-projeto
        run: npm start & sleep 5
