name: ci-pr
run-name: wokflow ci-pr sendo executado
on:
  pull_request:
    branches:
      - test
jobs:
  executa-testes:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o clone do repositório e muda para a branch correta (checkout)
        uses: actions/checkout@v5

      - name: instalar o node na versão 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Instalar as dependências de execução
        run: npm install

      - name: Executa os testes e do projeto
        run: npm test
